# travis config checker: http://config.travis-ci.org/

language: cpp

git:
  depth: false

before_install:
  - git fetch --tags

stages:
  - test
  - deploy

env:
  global:
    - CMAKE_BUILD_TYPE=Release

matrix:
  include:
  # OS X
  - &osx-template
    if: branch != coverity_scan
    stage: test
    name: "OS X - Xcode 8.3"
    os: osx
    osx_image: xcode8.3
    install: .travis/osx/install_deps.sh
    before_script: source .travis/osx/before_build.sh
    script: .travis/osx/build.sh

  - <<: *osx-template
    name: "OS X - Xcode 9.4"
    osx_image: xcode9.4

  # Ubuntu trusty
  - &ubuntu-trusty-template
    if: branch != coverity_scan
    stage: test
    name: "Ubuntu Trusty 14.04 GCC 5"
    os: linux
    dist: trusty
    before_script: source .travis/linux/before_build.sh
    script: .travis/linux/build.sh
    env: CXX_COMPILER=/usr/bin/g++-5
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - g++-5
          - libfftw3-dev
          - libgdal-dev

  - name: "Coverity Scan"
    if: branch = coverity_scan
    stage: test
    os: linux
    dist: trusty
    env: CXX_COMPILER=/usr/bin/clang++-5.0
    before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
    before_script: ":"
    script: "cat /home/travis/build/hlysunnaram/SIRIUS/cov-int/build-log.txt"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-5.0
          - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
            key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - clang-5.0
          - libstdc++-6-dev
          - libfftw3-dev
          - libgdal-dev
      coverity_scan:
        project:
          name: "hlysunnaram/SIRIUS"
          description: "Sirius coverity scan"
        notification_email: hlysunnaram@users.noreply.github.com
        build_command_prepend: "source .travis/linux/before_build.sh; cov-configure --comptype clangcc --compiler ${CXX_COMPILER}; sh .travis/linux/coverity_pre_build.sh"
        build_command: "make -j4"
        branch_pattern: coverity_scan

  - <<: *ubuntu-trusty-template
    name: "Ubuntu Trusty 14.04 GCC 6"
    env: CXX_COMPILER=/usr/bin/g++-6
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - g++-6
          - libfftw3-dev
          - libgdal-dev

  - <<: *ubuntu-trusty-template
    name: "Ubuntu Trusty 14.04 GCC 7"
    env: CXX_COMPILER=/usr/bin/g++-7
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - g++-7
          - libfftw3-dev
          - libgdal-dev

  - <<: *ubuntu-trusty-template
    name: "Ubuntu Trusty 14.04 GCC 7 - C++ static runtime"
    env: CXX_COMPILER=/usr/bin/g++-7 USE_CXX_STATIC_RUNTIME=ON
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - g++-7
          - libfftw3-dev
          - libgdal-dev

  - <<: *ubuntu-trusty-template
    name: "Ubuntu Trusty 14.04 Clang 4.0 - libc++"
    env: CXX_COMPILER=/usr/bin/clang++-4.0 ENABLE_CLANG_LIBCPP=ON
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-4.0
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - clang-4.0
          - libc++-dev
          - libfftw3-dev
          - libgdal-dev

  - <<: *ubuntu-trusty-template
    name: "Ubuntu Trusty 14.04 Clang 5.0 - libc++"
    env: CXX_COMPILER=/usr/bin/clang++-5.0 ENABLE_CLANG_LIBCPP=ON
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-5.0
          - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
            key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - clang-5.0
          - libc++-dev
          - libfftw3-dev
          - libgdal-dev

  - <<: *ubuntu-trusty-template
    name: "Ubuntu Trusty 14.04 Clang 6.0 - libc++"
    env: CXX_COMPILER=/usr/bin/clang++-6.0 ENABLE_CLANG_LIBCPP=ON
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-6.0
          - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
            key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - clang-6.0
          - libc++-dev
          - libfftw3-dev
          - libgdal-dev

  - <<: *ubuntu-trusty-template
    name: "Ubuntu Trusty 14.04 Clang 6.0 - libc++ - C++ static runtime"
    env: CXX_COMPILER=/usr/bin/clang++-6.0 ENABLE_CLANG_LIBCPP=ON USE_CXX_STATIC_RUNTIME=ON
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-6.0
          - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
            key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - clang-6.0
          - libc++-dev
          - libfftw3-dev
          - libgdal-dev

  - <<: *ubuntu-trusty-template
    name: "Ubuntu Trusty 14.04 Clang 4.0 - stdlibc++ 5"
    env: CXX_COMPILER=/usr/bin/clang++-4.0 ENABLE_CLANG_LIBCPP=OFF
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-4.0
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - clang-4.0
          - libstdc++-5-dev
          - libfftw3-dev
          - libgdal-dev

  - <<: *ubuntu-trusty-template
    name: "Ubuntu Trusty 14.04 Clang 5.0 - stdlibc++ 6"
    env: CXX_COMPILER=/usr/bin/clang++-5.0 ENABLE_CLANG_LIBCPP=OFF
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-5.0
          - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
            key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - clang-5.0
          - libstdc++-6-dev
          - libfftw3-dev
          - libgdal-dev

  - <<: *ubuntu-trusty-template
    name: "Ubuntu Trusty 14.04 Clang 6.0 - stdlibc++ 7"
    env: CXX_COMPILER=/usr/bin/clang++-6.0 ENABLE_CLANG_LIBCPP=OFF
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-6.0
          - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
            key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - clang-6.0
          - libstdc++-7-dev
          - libfftw3-dev
          - libgdal-dev

  - <<: *ubuntu-trusty-template
    name: "Ubuntu Trusty 14.04 Clang 6.0 - stdlibc++ 7 - C++ static runtime"
    env: CXX_COMPILER=/usr/bin/clang++-6.0 ENABLE_CLANG_LIBCPP=OFF USE_CXX_STATIC_RUNTIME=ON
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-6.0
          - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
            key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - clang-6.0
          - libstdc++-7-dev
          - libfftw3-dev
          - libgdal-dev

  # Docker
  - &centos-7-template
    if: branch != coverity_scan
    name: "CentOS Docker"
    stage: test
    os: linux
    services:
      - docker
    install: .travis/docker/install_deps.sh
    before_script: source .travis/docker/before_build.sh
    script: .travis/docker/build.sh

  - <<: *centos-7-template
    name: "CentOS Docker - Deploy"
    stage: deploy
    deploy:
      provider: script
      script: .travis/docker/deploy.sh
      on:
        branch: master
