#!/bin/bash

set -ev

SIRIUS_REVISION_COMMIT=${TRAVIS_COMMIT}

echo "SIRIUS_VERSION=${SIRIUS_VERSION}"
echo "SIRIUS_REVISION_COMMIT=${SIRIUS_REVISION_COMMIT}"
echo "PROJECT_DIR=${PROJECT_DIR}"
echo "INSTALL_DIR=${INSTALL_DIR}"
echo "CXX_COMPILER=${CXX_COMPILER}"

# create makefile project
cmake ${PROJECT_DIR} \
    -G "Unix Makefiles" \
    -DCMAKE_CXX_COMPILER="${CXX_COMPILER}" \
    -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE}" \
    -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR} \
    -DSIRIUS_VERSION="${SIRIUS_VERSION}" \
    -DSIRIUS_REVISION_COMMIT="${SIRIUS_REVISION_COMMIT}" \
    -DENABLE_CACHE_OPTIMIZATION=ON \
    -DENABLE_GSL_CONTRACTS=ON \
    -DENABLE_LOGS=ON \
    -DBUILD_TESTING=ON \
    -DENABLE_DOCUMENTATION=OFF \
    -DENABLE_CLANG_LIBCPP=${ENABLE_CLANG_LIBCPP} \
    -DUSE_CXX_STATIC_RUNTIME=${USE_CXX_STATIC_RUNTIME}